apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterrolebinding-library
  namespace: library-ns
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: library-ns

### If you are not creating this ClusterRoleBinding, you need to run the below command....
### oc policy add-role-to-user edit system:serviceaccount:library-ns:pipeline -n library-ns
